# Generated by Django 4.2.3 on 2023-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_category_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, default='Car', max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
