# Generated by Django 4.2.3 on 2023-08-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
