# Generated by Django 4.2.3 on 2023-08-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_category_rename_price_bid_bid_listing_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
