# Generated by Django 4.2.3 on 2023-08-09 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_category_listing_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winningbid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing', models.ManyToManyField(blank=True, related_name='winner', to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
