# Generated by Django 4.2.3 on 2023-08-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_bidwinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidwinner',
            name='listing',
        ),
        migrations.AddField(
            model_name='bidwinner',
            name='listing',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
